from enum import Enum

class ConversationState(str, Enum):
    IDLE = "IDLE"
    WAITING_TUTOR_NAME = "WAITING_TUTOR_NAME"
    WAITING_PET_NAME = "WAITING_PET_NAME"
    WAITING_SERVICE_TYPE = "WAITING_SERVICE_TYPE"
    WAITING_DATE = "WAITING_DATE"
    WAITING_TIME = "WAITING_TIME"

class AppointmentStatus(str, Enum):
    DRAFT = "DRAFT"
    PENDING_CONFIRMATION = "PENDING_CONFIRMATION"
    CONFIRMED = "CONFIRMED"
    CANCELLED = "CANCELLED"
